
apiVersion: v1
kind: Service
metadata:
  name: stock-api
  labels:
    app: widgetario
    component: stock-api
spec:
  selector:
    app: widgetario
    component: stock-api
  ports:
    - port: 8080
      targetPort: http
  type: ClusterIP