apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: widgetario
    
spec:
  selector:
    matchLabels:
        app: widgetario
        component: web
  template:
    metadata:
      labels: 
        app: widgetario
        component: web
    spec:
      containers:
        - name: app
          image: widgetario/web:21.03
          ports:
            - containerPort: 80
              name: http