apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
  labels:
    app: widgetario
    component: stock-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: widgetario
  template:
    metadata:
      labels:
        app: widgetario
        component: stock-api
    spec:
      containers:
        - name: stock-api
          image: widgetario/stock-api:21.03
          ports:
            - containerPort: 8080
              name: http