apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      containers:
        - name: products-db
          image: widgetario/products-db:21.03
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: products-db-service
spec:
  selector:
    app: products-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
