# This is a Kubernetes manifest file for deploying a simple products API application.
apiVersion: v1
kind: Service
metadata:
  name: products-api
  labels:
    
    app: widgetario
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: widgetario
    component: products-api
  type: ClusterIP
